// Copyright (c)  NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// THIS FILE WAS GENERATED BY CMAKE AUTOMATICALLY
//
// SEE ZitiNativeApiForDotnetCore\CMakeLists.txt and look for generateDotnetStatus.ps1

namespace OpenZiti {
    public enum ZitiStatus {
        ZITI_OK = 0,
         ZITI_CONFIG_NOT_FOUND = -1,
         ZITI_JWT_NOT_FOUND = -2,
         ZITI_JWT_INVALID = -3,
         ZITI_JWT_INVALID_FORMAT = -4,
         ZITI_PKCS7_ASN1_PARSING_FAILED = -5,
         ZITI_JWT_SIGNING_ALG_UNSUPPORTED = -6,
         ZITI_JWT_VERIFICATION_FAILED = -7,
         ZITI_ENROLLMENT_METHOD_UNSUPPORTED = -8,
         ZITI_ENROLLMENT_CERTIFICATE_REQUIRED = -9,
         ZITI_KEY_GENERATION_FAILED = -10,
         ZITI_KEY_LOAD_FAILED = -11,
         ZITI_CSR_GENERATION_FAILED = -12,
         ZITI_INVALID_CONFIG = -13,
         ZITI_AUTHENTICATION_FAILED = -14,
         ZITI_NOT_AUTHORIZED = -15,
         ZITI_CONTROLLER_UNAVAILABLE = -16,
         ZITI_GATEWAY_UNAVAILABLE = -17,
         ZITI_SERVICE_UNAVAILABLE = -18,
         ZITI_EOF = -19,
         ZITI_TIMEOUT = -20,
         ZITI_CONNABORT = -21,
         ZITI_INVALID_STATE = -22,
         ZITI_CRYPTO_FAIL = -23,
         ZITI_CONN_CLOSED = -24,
         ZITI_INVALID_POSTURE = -25,
         ZITI_MFA_EXISTS = -26,
         ZITI_MFA_INVALID_TOKEN = -27,
         ZITI_MFA_NOT_ENROLLED = -28,
         ZITI_NOT_FOUND = -29,
         ZITI_DISABLED = -30,
         ZITI_PARTIALLY_AUTHENTICATED = -31,
         ZITI_INVALID_AUTHENTICATOR_TYPE = -32,
         ZITI_INVALID_AUTHENTICATOR_CERT = -33,
         ZITI_INVALID_CERT_KEY_PAIR = -34,
         ZITI_WTF = -111,

    }
}

