<#
.SYNOPSIS
Generates a dotnet (csharp) enum from the OpenZiti c sdk errors.h file

.DESCRIPTION
This script will:
    - parse the errors.h file finding any #define'd symblols
    - apply a regex to find the name of the symbol and the value
    - write the values into an enum

.PARAMETER OutputPath
    The path the enum should be written into

.OUTPUTS
None.

.EXAMPLE
PS> .\generateDotnetStatus.ps1
#>
param (
    [Parameter(Mandatory=$true)] [string]$SourceFile,
    [Parameter(Mandatory=$true)] [string]$OutputPath
)

$pattern = '.*#define\s+(\w+)\s+\((-?\d+)\)'
$statuses = $(select-string "#define ZITI_"  -Path $SourceFile)

# Initialize an empty array to store the transformed lines
$transformedLines = @()

$total=$statuses.Count
# Read the input file line by line
foreach ($line in $statuses) {
    # Check if a match was found, -match creates a $Matches automatically (see below)
    if ($line -match $pattern) {
        # Extract the matched values from the regex groups
        $name = $Matches[1]
        $value = $Matches[2]
        # Create the desired output string
        $outputLine = "        $name = $value,"
        
        # Add the transformed line to the array
        $transformedLines += $outputLine + "`r`n"
    } else {
        # If no match was found, add the original line to the array
        $transformedLines += $line
    }
}

$fileContents = "// Copyright (c)  NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the `"License`");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an `"AS IS`" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// THIS FILE WAS GENERATED BY CMAKE AUTOMATICALLY
//
// SEE ZitiNativeApiForDotnetCore\CMakeLists.txt and look for generateDotnetStatus.ps1

namespace OpenZiti {
    public enum ZitiStatus {
" + $transformedLines + "
    }
}
"

Set-Content -Path $OutputPath -Value $fileContents
"enum written to $OutputPath"