#set(CMAKE_SYSTEM_NAME Windows)
#set(CMAKE_SYSTEM_PROCESSOR Win32)
#set(CMAKE_GENERATOR_PLATFORM:INTERNAL Win32)
set(CMAKE_GENERATOR_PLATFORM "win32")

#set(triple i686-w64-mingw32)
#set(CMAKE_C_COMPILER ${triple}-gcc)
#set(CMAKE_CXX_COMPILER ${triple}-g++)
#
#set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
#set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
